[package]
authors = ["Jayson Reis (jaysonsantos) <santosdosreis@gmail.com>"]
license = "MIT"
name = "librusty-platter"
readme = "README.md"
version = "0.1.0"

[dependencies]
ring = "0.7.3"

[dev-dependencies]
tempdir = "0.3.5"
