[package]
authors = ["Jayson Reis (jaysonsantos) <santosdosreis@gmail.com>"]
license = "MIT"
name = "librusty-platter"
readme = "README.md"
version = "0.1.0"

[dependencies]
data-encoding = "2.0.0-rc.1"
ring = "0.9.4"
serde = "1.0.4"
serde_derive = "1.0.4"
serde_json = "1.0.2"

# [dev-dependencies]
tempdir = "0.3.5"
